### PR TITLE
Use strong typed enum for RegType

### PR DESCRIPTION
**Pull request by miscco**
It bit me in a previous PR that RegType is not type safe.

I had some time at hand and went for it

### CODE REVIEW

**Comment by daniel-schuermann** [comment]
So, the first commit looks useful to avoid these naming issues in future. Also, we don't use boolean algebra on this type. For the second commit, I'm not sure if I like this idea for two reasons:
1) the naming: although it makes somehow sense, often it is not the question whether a variable is a scalar or vector value but rather if it lives in the linear or logical CFG. These are to different things.
2) the semantics: That said, we might prefer something like the is_linear() check and maybe an is_vgpr() check, both of them including the linear_vgprs. (I'm actually not sure if we do it correctly everywhere but the linear_vgpr is quite rare anyway.)
Question is also if these functions should be part of Temp or RegClass. @pendingchaos? And you might have noticed that our code style is all over the place... it's definitely our plan to get this consistent.

**Comment by miscco** [comment]
Yeah I wasn't sure about the second one either. I just did a search/replace for `.type() == {s|v}gpr` and noticed that it is used all over the place. However, as you said it is not 100% clear whether these match up and are semantically identical

Also I noticed quite a lot of the form `getTemp().type() == {s|v}gpr`. However for `Operand` and `Definition` it is even more unclear what a correct name would be as they have a separate `type()` method. 

That said finding good names would greatly improve the clarity of the code. Even if we have different identical functions for the different use cases

**Comment by miscco** [comment]
I have dropped the second commit. I think it is best to merge the change to typesafe enums and then figure out what good helper functions are

**Comment by miscco** [comment]
Hey, 
is it ok to merge this PR without the new helper and decide on those hellpers later or should I try to come up with better naming/semantics?

I wouldnt want to rebase multiple times if we want to work on the design of helpers

**Comment by daniel-schuermann** [comment]
I understand :)
merged manually.

**Pull request closed without merging**
